#ifndef MONO_SLAM_GEOMETRY_SOLVER_ESTIMATE_ESSENTIAL_MATRIX_H_
#define MONO_SLAM_GEOMETRY_SOLVER_ESTIMATE_ESSENTIAL_MATRIX_H_

namespace geometry
{
  
} // namespace geometry

 
#endif  // MONO_SLAM_GEOMETRY_SOLVER_ESTIMATE_ESSENTIAL_MATRIX_H_